version: "3.7"

services:
  microservice:
    image: ldap-search-service:1.0.0
    environment:
      - LDAP_URL=ldap://apacheds:10389
    ports:
      - "8080:8080"
      - "9090:9090"
    labels:
      kompose.service.type: loadbalancer
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
          # cpus: '2.0'
          cpus: '4.0'

  apacheds:
    build:
      context: src/main/docker
      dockerfile: Dockerfile.apacheds
    image: "apacheds:2.0.0.AM26"
    ports:
      - "10389:10389"
      - "10636:10636"
    labels:
      kompose.service.type: nodeport
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
          cpus: '1.0'